### ISSUE TITLE
引用

### ISSUE THREAD

**Issue by baiminai** [VeiZhang/AndroidFFmpeg#2]
在引用方法会出现错误ERROR: Failed to resolve: com   Affected Modules: app问题。
我的项目没有问题，但在引用你这个后出现错误，去除引用后恢复正常

**Comment by VeiZhang** [comment]
@baiminai 你是如何引用的？demo能正常运行？

**Comment by baiminai** [comment]
implementation 'com.excellence:ffmpeg:_latestVersion' 依赖@VeiZhang

**Comment by VeiZhang** [comment]
@baiminai 改成指定版本试试咯
