### ISSUE TITLE
如何减小库的大小?

### ISSUE THREAD

**Issue by susu1009** [VeiZhang/AndroidFFmpeg#3]
你好兄弟，
我使用了你的库，它与我的项目完美配合。但是库的大小太大了，有没有办法减小这个库的大小？

谢谢！

**Comment by VeiZhang** [comment]
@susu1009 你是使用了部分CPU架构的lib库还是使用了所有CPU架构的lib？

**Comment by susu1009** [comment]
我正在使用一个包含所有CPU架构的库，因为现在我想将应用程序推送到存储库中，我必须拥有所有CPU架构。

**Comment by VeiZhang** [comment]
@susu1009 如果没有使用x86的架构，那你可以只使用armeabi架构，可以兼容arm-v7

**Comment by VeiZhang** [comment]
@susu1009 还有一个办法，减小可执行文件大小，你自己去编译可执行文件 **（删减一些不需要的编码解码配置）** ，然后把编译生成的可执行文件拷贝到路径`Context.getFilesDir() + ffmpeg`。依赖库里面判断是否存在可执行文件，当不存在时，会拷贝到该路径下 [FFmpeg.java#L115](https://github.com/VeiZhang/AndroidFFmpeg/blob/6c3b438e7d9cacf4e0d8d320b2f08ba31ba1c13e/FFmpeg-java/src/main/java/com/excellence/ffmpeg/FFmpeg.java#L115)。
