### ISSUE TITLE
64bit support?

### ISSUE THREAD

**Issue by eslam2010011** [VeiZhang/AndroidFFmpeg#4]
Hello and many thanks for your ffmpeg library for Android.

After reading about the new 64bit requirement for Android of native libraries, I noted that your library is not stored in Libs but in Assets. Instructions from Google says to verify for the presence of 64bit by looking at the Directory-names. If I unzip, it only contains Arm and x86 directories and does not give an indication if 64 libs is included.

See this:
https://developer.android.com/distribute/best-practices/develop/64-bit

Can you confirm that your library is OK with Google's new requirements?

Thanks.

**Comment by VeiZhang** [comment]
@eslam2010011 The library supports 64bit, but it is not a `*.so` file, but a executable file for android.
