### ISSUE TITLE
是否是不支持ts

### ISSUE THREAD

**Issue by zijin2014** [VeiZhang/AndroidFFmpeg#5]

**Comment by VeiZhang** [comment]
@wjj201411 ts流是为了做什么？我有做过ts流录制，可行。遇到的问题是，服务器限制，同时间只能录制一个流，多个流会被限制导致失败。

**Comment by zijin2014** [comment]
> @wjj201411 ts流是为了做什么？我有做过ts流录制，可行。遇到的问题是，服务器限制，同时间只能录制一个流，多个流会被限制导致失败。

本地有ts,mov格式视频，需要转码和裁剪ts,mov格式

**Comment by VeiZhang** [comment]
@wjj201411 你用PC端的FFmpeg工具试试，直接用cmd执行你的命令，看看是什么效果，一般PC上能执行ok的，那Android端执行命令应该也可以。

**Comment by zijin2014** [comment]
> @wjj201411 你用PC端的FFmpeg工具试试，直接用cmd执行你的命令，看看是什么效果，一般PC上能执行ok的，那Android端执行命令应该也可以。

![image](https://user-images.githubusercontent.com/9624595/67836460-a4482a80-fb27-11e9-8448-0481e85706fc.png)
我执行完找不到转换后的视频，这是怎么回事呢？确实执行到了onSuccess

**Comment by VeiZhang** [comment]
@wjj201411 看看Log有什么信息打印，命令写的有问题吧，多了一个FFmpeg？
正确的命令不应该是这样吗`/data/use/.../ffmpeg -y -i ...`？

**Comment by zijin2014** [comment]
> @wjj201411 看看Log有什么信息打印，命令写的有问题吧，多了一个FFmpeg？
> 正确的命令不应该是这样吗`/data/use/.../ffmpeg -y -i ...`？
/data/use/.../，，我一直以为是直接命令行就行，尴尬
