### ISSUE TITLE
没有启用h264

### ISSUE THREAD

**Issue by kuerjinjin** [VeiZhang/AndroidFFmpeg#6]
不知道是没有编译libx264库，还是编译了没有启用！反正涉及到h264的都不能用！会报错：Unknown encoder 'h264'

**Comment by VeiZhang** [comment]
@kuerjinjin 我测了H264，没发现问题。发一下你的测试命令看看

**Comment by kuerjinjin** [comment]
测试的是这个命令：ffmpeg -i test.mp4 -vcodec h264 -an -f m4v test1.264

**Comment by VeiZhang** [comment]
@kuerjinjin 抱歉，确实是没有开启配置，你可以按照需要参考 **https://github.com/WritingMinds/ffmpeg-android** 自己去编译，然后替换掉库里面的文件就可以了 https://github.com/VeiZhang/AndroidFFmpeg/issues/3#issuecomment-507936621
