### ISSUE TITLE
请问作者,可以加上libx264库的吗,在编译出安卓的ffmpeg可执行文件

### ISSUE THREAD

**Issue by at89s52rc** [VeiZhang/AndroidFFmpeg#9]
非常感谢作者,编译好了安卓上的可执行文件,请问作者,可以加上libx264库的吗,在编译出安卓的ffmpeg可执行文件,谢谢

**Comment by VeiZhang** [comment]
@at89s52rc 如果紧急的话，需要你自己处理一下，目前没有时间处理，后面会完善。
